'use client'
import vazirFont from "@/constants/localFonts";
import '../globals.css'
import '../style.css'

import "react-widgets/styles.css";

import {Toaster} from "react-hot-toast";
import Provider from "../(panel)/Provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SideBar from "@/app/(panel)/SideBar";
import {useEffect} from "react";
import {ThemeProvider} from "next-themes";

// export const metadata = {
//     title: 'next shop panel',
//     description: 'Generated by ali bahrampoor',
// }

function RootLayout({children}) {

    useEffect(() => {
        import('preline')
    }, [])

    return (
        <html lang="en" dir={'rtl'} className={'dark'}>
        <head>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>بخش کاربران </title>
            <meta
                name="description"
                content="this App is used for fronthooks next.js course"
            />
        </head>
        <body className={`${vazirFont.variable} font-sans`} suppressHydrationWarning={true}>
        <Provider>

            <ThemeProvider attribute={'class'}>
                <div>
                    <Header/>
                    <div className="grid grid-cols-12 h-screen ">
                        <aside className="col-span-12 lg:col-span-3 xl:col-span-2 hidden lg:block">
                            <SideBar/>
                        </aside>
                        <div
                            className={`col-span-12 lg:col-span-9 xl:col-span-10 h-screen flex flex-col  dark:bg-slate-800 ring-1 ring-slate-900/5  dark:border-gray-700 dark:divide-gray-700`}>
                            {children}
                        </div>
                    </div>
                </div>
            </ThemeProvider>
            <Footer/>
            <Toaster/>

        </Provider>
        </body>
        </html>
    )
}

export default RootLayout