import vazirFont from "@/constants/localFonts";
import '../globals.css'
import '../style.css'
import Header from '../../components/Header'
import {Toaster} from "react-hot-toast";
import Provider from "./Provider";
import Footer from "@/components/Footer";
import SideBar from "@/app/(panel)/SideBar";


export const metadata = {
    title: 'next shop panel', description: 'Generated by ali bahrampoor',
}

export default function RootLayout({children}) {
    return (<html lang="en" dir={'rtl'}>
    <body className={`${vazirFont.variable} font-sans`} suppressHydrationWarning={true}>
    <Provider>
        <Header/>
        <div className="grid grid-cols-4 bg-white h-screen">
            <div className="col-span-1 bg-gray-100 overflow-y-auto ">
                <SideBar/>
            </div>
            <div className="col-span-3 overflow-y-auto p-4">
                {children}
            </div>
        </div>
        <Footer/>
        <Toaster/>
    </Provider>
    </body>
    </html>)
}
