'use client'
import vazirFont from "@/constants/localFonts";
import '../globals.css'
import '../style.css'
import Header from '../../components/Header'
import {Toaster} from "react-hot-toast";
import Provider from "./Provider";
import Footer from "@/components/Footer";
import SideBar from "@/app/(panel)/SideBar";
import {useEffect} from "react";


export const metadata = {
    title: 'next shop panel', description: 'Generated by ali bahrampoor',
}

export default function RootLayout({children}) {
    useEffect(() => {
        import('preline')
    }, [])
    return (<html lang="en" dir={'rtl'}>
    <body className={`${vazirFont.variable} font-sans`} suppressHydrationWarning={true}>
    <Provider>
        <Header/>
        <div className="grid grid-cols-4 bg-white h-screen ">

            <SideBar/>

            <div className="col-span-3 overflow-y-auto p-4">
                {children}
            </div>
        </div>
        <Footer/>
        <Toaster/>
    </Provider>
    </body>
    </html>)
}
