import vazirFont from "@/constants/localFonts";
import Provider from "@/app/(panel)/Provider";
import '../globals.css'
import '../style.css'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" dir={'rtl'}>
        <Provider>
            <body className={`${vazirFont.variable} font-sans`} suppressHydrationWarning={true}>{children}</body>
        </Provider>
        </html>
    )
}
