// create user
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

// create fast user
export const CREATE_FAST_USER_REQUEST = 'CREATE_FAST_USER_REQUEST'
export const CREATE_FAST_USER_SUCCESS = 'CREATE_FAST_USER_SUCCESS'
export const CREATE_FAST_USER_FAILURE = 'CREATE_FAST_USER_FAILURE'
