'use client'
import vazirFont from "@/constants/localFonts";
import '../../globals.css'
import '../../style.css'


import {Toaster} from "react-hot-toast";
import Provider from "../../(panel)/Provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SideBar from "@/app/(panel)/SideBar";
import {useEffect} from "react";
import {ThemeProvider} from "next-themes";
import { createTheme } from '@mui/material/styles';

export const metadata = {
    title: 'next shop panel', description: 'Generated by ali bahrampoor',
}

export default function RootLayout({children}) {
    const theme = createTheme({
        direction: 'rtl',
    });

    useEffect(() => {
        import('preline')
    }, [])

    return (
        <html lang="en" dir={'rtl'} className={'dark'}>
        <body className={`${vazirFont.variable} font-sans`} suppressHydrationWarning={true}>
        <Provider>
            <ThemeProvider attribute={'class'}>
                <div className="">
                    <Header/>
                    <div className="grid grid-cols-12 h-screen ">
                        <aside className="col-span-12 lg:col-span-3 xl:col-span-2 hidden lg:block">
                            <SideBar/>
                        </aside>
                        <div
                            className={`col-span-12 lg:col-span-9 xl:col-span-10 h-screen flex flex-col  dark:bg-slate-800 ring-1 ring-slate-900/5  dark:border-gray-700 dark:divide-gray-700`}>
                            {children}
                        </div>
                    </div>
                </div>
            </ThemeProvider>
            <Footer/>
            <Toaster/>
        </Provider>
        </body>
        </html>
    )
}
